### ISSUE TITLE
This project was not working properly in my Mac.

### ISSUE THREAD

**Issue by bnagarjuna** [QuickBlox/AR-Locator-ios#1]
i got this error.......

ld: warning: ignoring file /Users/Nagarjuna/Downloads/AR-Locator-ios-master/Libs/Quickblox.framework/Quickblox, missing required architecture x86_64 in file /Users/Nagarjuna/Downloads/AR-Locator-ios-master/Libs/Quickblox.framework/Quickblox (3 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_PagedRequest", referenced from:
      objc-class-ref in MapARViewController.o
  "_OBJC_CLASS_$_QBASessionCreationRequest", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_QBAuth", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_QBLPlacePagedResult", referenced from:
      objc-class-ref in MapARViewController.o
  "_OBJC_CLASS_$_QBLocation", referenced from:
      objc-class-ref in MapARViewController.o
  "_OBJC_CLASS_$_QBSettings", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

please give help how to solve it......

**Comment by soulfly** [comment]
It's too old and we don't support it

**Comment by soulfly** [comment]
http://quickblox.com/developers/IOS
